groups:
    - bash
    - developer
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Mathieu
    homebrewalt:
        cask_apps:
            - vagrant
            - phpstorm
            - sequel-pro
