recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
attributes:
    homebrewalt:
        apps:
            - git
        cask_apps:
            - google-chrome
            - firefox
        cask_fonts:   
            - inconsolata
    nodejs:
        apps:
            - bower
